/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_NativeHelpers */

#ifndef _Included_org_example_NativeHelpers
#define _Included_org_example_NativeHelpers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_NativeHelpers
 * Method:    renderTriangleToMTLTexture
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_example_NativeHelpers_renderTriangleToMTLTexture
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_NativeHelpers
 * Method:    loadBitmapFromPNG
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_NativeHelpers_loadBitmapFromPNG
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_example_NativeHelpers
 * Method:    releaseBitmapFromJPG
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_NativeHelpers_releaseBitmapFromJPG
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
