/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_NativeHelpers */

#ifndef _Included_org_example_NativeHelpers
#define _Included_org_example_NativeHelpers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_NativeHelpers
 * Method:    loadIOSurfaceFromPNG
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_NativeHelpers_loadIOSurfaceFromPNG
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_example_NativeHelpers
 * Method:    getMTLTextureFromIOSurface
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_NativeHelpers_getMTLTextureFromIOSurface
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_NativeHelpers
 * Method:    getOpenGLTextureFromIOSurface
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_NativeHelpers_getOpenGLTextureFromIOSurface
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_NativeHelpers
 * Method:    loadMTLTextureFromPNG
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_NativeHelpers_loadMTLTextureFromPNG
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_example_NativeHelpers
 * Method:    getMTLTextureSize
 * Signature: (J)Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_org_example_NativeHelpers_getMTLTextureSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_NativeHelpers
 * Method:    MTLTextureToByteArray
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_example_NativeHelpers_MTLTextureToByteArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_NativeHelpers
 * Method:    scaleMTLTexture
 * Signature: (JJD)Z
 */
JNIEXPORT jboolean JNICALL Java_org_example_NativeHelpers_scaleMTLTexture
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     org_example_NativeHelpers
 * Method:    copyMTLTexture
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_example_NativeHelpers_copyMTLTexture
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_example_NativeHelpers
 * Method:    releaseMTLTexture
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_NativeHelpers_releaseMTLTexture
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_NativeHelpers
 * Method:    loadOpenGLTextureFromPNG
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_NativeHelpers_loadOpenGLTextureFromPNG
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_example_NativeHelpers
 * Method:    createOpenGLContext
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_example_NativeHelpers_createOpenGLContext
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_example_NativeHelpers
 * Method:    saveOpenGLTextureToPNG
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_example_NativeHelpers_saveOpenGLTextureToPNG
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_example_NativeHelpers
 * Method:    releaseOpenGLTexture
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_NativeHelpers_releaseOpenGLTexture
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_NativeHelpers
 * Method:    getTextureFromVolatileImage
 * Signature: (Ljava/awt/image/VolatileImage;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_NativeHelpers_getTextureFromVolatileImage
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_example_NativeHelpers
 * Method:    RenderQueueFlushAndInvokeNow
 * Signature: (Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_org_example_NativeHelpers_RenderQueueFlushAndInvokeNow
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
