/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_NativeHelpers */

#ifndef _Included_org_example_NativeHelpers
#define _Included_org_example_NativeHelpers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_NativeHelpers
 * Method:    sayHallo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_NativeHelpers_sayHallo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
